services:
  - type: web
    name: giftgive-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend/main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.5 # Hãy kiểm tra phiên bản python bạn dùng